name: Build Container docker hub
on: push
jobs:
    build-container:
        name: Build Container docker hub
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACESS_TOKEN }}
        - name: Build and push to Docker Hub
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: catiaportimao/nextwebapp:latest, catiaportimao/nextwebapp:${{ github.run_number}}


        